import React from 'react';

const MainDashboard = () => {
    return (
        <div className='bg-[#111c44] text-white p-3 h-full rounded-2xl'>
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
            Main Dashboard
            <br />
        </div>
    );
};

export default MainDashboard;